# Ansible Inventory — Auto-generated by Terraform
# Do NOT edit manually. Re-run 'terraform apply' to regenerate.

[servers]
%{ for name, instance in ubuntu ~}
${name} ansible_user=${instance.user}
${name} ansible_host=${instance.public_ip}
%{ endfor ~}

%{ for name, instance in redhat ~}
${name} ansible_user=${instance.user}
${name} ansible_host=${instance.public_ip}
%{ endfor ~}

%{ for name, instance in amazon ~}
${name} ansible_user=${instance.user}
${name} ansible_host=${instance.public_ip}
%{ endfor ~}

[all:vars]
ansible_ssh_private_key_file=${ssh_key_path}
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false